imports:
    - { resource: config.yml }

parameters:
    cache_type: array

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration


       # run firePHP console
        firephp:
            type:   firephp
            level:  info
        chromephp:
            type:   chromephp
            level:  info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

# disable caching in the dev environment only
#doctrine_cache:
#    providers:
#        my_markdown_cache:
#            type: array
# The array type is basically a "fake" cache: it won't ever store anything
# Test:
# Reload page always take additional 1 sec time, since its takes entire sec to sleep()